spring:
  datasource:
    username: dev
    password: 123
    url: jdbc:h2:file:./data/cloud-disk
  h2:
    console:
      enabled: true
storage:
  dir: './file'
mybatis-plus:
  type-enums-package: com.xb.cloud.disk.enums